### Into to data science

- реляционный вид данных
- матричное представление 
- паплайн обработки данных
    - discovering structure 
    - descriptive analysis 
    - dealing with missing 
    - types of variables 
    - nominal \ categorical varibales
    - dummy \ OHE
    - pandas-profiling 
    - accelarations (numpy, numba, desk)
- numpy
- pandas 
    - types
    - DataFrame
    - slicing
    - methods
    - data transformations (group by, pivot) 
    

### numpy

In [1]:
import numpy as np

In [5]:
a = np.arange(15)
b = np.arange(15, 30)

In [6]:
type(b)

numpy.ndarray

In [10]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
a.shape

(15,)

In [13]:
a.ndim

1

In [19]:
a.reshape(3,5).T.dot(b.reshape(3,5))

array([[350, 365, 380, 395, 410],
       [410, 428, 446, 464, 482],
       [470, 491, 512, 533, 554],
       [530, 554, 578, 602, 626],
       [590, 617, 644, 671, 698]])

In [20]:
l = [1,2,3]
ln = np.array(l)

In [24]:
ln = np.array(l, dtype=complex)

In [ ]:
ln

#### zeros \ ones

In [41]:
z = np.zeros((3,4))
np.fill_diagonal(z, 1)

In [42]:
z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### linspace

In [29]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### product 

In [33]:
a = np.arange(15).reshape(3,5)
b = np.arange(15, 30).reshape(3,5)

In [34]:
a * b

array([[  0,  16,  34,  54,  76],
       [100, 126, 154, 184, 216],
       [250, 286, 324, 364, 406]])

In [36]:
a @ b.T

array([[ 180,  230,  280],
       [ 605,  780,  955],
       [1030, 1330, 1630]])

#### random

In [43]:
np.random.random_sample((3,4))

array([[0.87710091, 0.44336631, 0.8677405 , 0.32870597],
       [0.97931838, 0.03264175, 0.84217931, 0.86801618],
       [0.79537719, 0.18709659, 0.30194522, 0.81835995]])

### pandas